### ISSUE TITLE
Support for multi chef-servers

### ISSUE THREAD

**Issue by guilhem** [jonlives/knife-spork#176]
Hi @jonlives,
first of all thanks for your work!

I really like the idea behind `spork`, it can really help us.
The only problem we have now to use it is lack of support for multiple chef-server.

For example it's really useful when you use a chef-entreprise for production and chef oss for dev platform (to limit useless license usage).
It's also useful when you dedicace some server by env for isolation or scaling purpose :)

I don't know how to write this code and how much is the impact... but it can become a must have :)

**Comment by jonlives** [comment]
@guilhem thanks! Supporting separate chef servers is a little tricky here, because spork is ultimately a knife plugin, and runs under the config loaded from your knife.rb config file in the same way as any other knife plugin.

knife, and all plugins under it, supports specifying an alternate config file on the command line with the -c option, so you could easily do e.g. `knife spork upload apache -c ~/.chef/knife-production.rb` and `knife spork upload apache -c ~/.chef/knife-development.rb` where those config files define the details for the relevant Chef servers.

**Comment by guilhem** [comment]
@jonlives :cry: but I understand :)

**Comment by chazzly** [comment]
@guilhem - are you trying to perform a spork command to multiple chef servers at the SAME TIME?  That would be problematic.  If not, we have a very similar situation, one chef server we use for our own dev / testing, and our production chef server.  I put together a simple shell script which switches between the two:
- it copies either knife.dev or knife.prod to knife.rb
- it then checks out and does a pull to the appropriate git repositories.
- We also use it a reference to populate our command prompt, so that as we maneuver around our chef repo, we know which server we're configured to talk to.

**Comment by jonlives** [comment]
https://github.com/knife-block/knife-block is a pretty good tool for doing similar stuff too :)

**Comment by guilhem** [comment]
@chazzly no, not at the same time.
we have (to resume... we have many more than that ;)):
- "dev server" with many `dev01`, `dev02`... environments
- "integration" server
- "prod" server

As many people must be able to use it and promote cookbooks (based on there rights on the chef-server), I want to have a simplistic tool with a shared configuration.
